#!/bin/bash -ex

GULP=./node_modules/.bin/gulp

function install() {
    npm install
    touch $GULP  # installer doesn't always touch this after a build, so we do.
}

# Rebuild Gulp if missing or outdated.
[ -e $GULP ] || install
[ gulpfile.js -nt $GULP ] && install

$GULP
exec $GULP watch
